import Datastore from 'nedb-promises';
import { Meeting } from 'src/meetings/meeting.model';

const initialMeetings: Meeting[] = [
  {
    id: 6,
    title: 'Public Speaking Mastery',
    description: 'Develop your public speaking skills with practical exercises',
    date: new Date(2023, 5, 8, 17, 30, 0, 0),
    availableSeats: 18,
    status: 'Active',
    level: 'Intermediate',
    attendies: ['Grace', 'Mark', 'Olivia'],
    city: 'Los Angeles',
  },
  {
    id: 7,
    title: 'Mindfulness Meditation Session',
    description: 'Guided meditation for relaxation and wellbeing',
    date: new Date(2023, 6, 15, 19, 0, 0, 0),
    availableSeats: 15,
    status: 'Active',
    level: 'All Levels',
    attendies: ['Emma', 'Ryan', 'Sophia'],
    city: 'Sydney',
  },
  {
    id: 8,
    title: 'Debating Club Meeting',
    description: 'Engage in lively debates on various topics',
    date: new Date(2023, 7, 3, 18, 30, 0, 0),
    availableSeats: 20,
    status: 'Active',
    level: 'Advanced',
    attendies: ['Noah', 'Ava', 'William'],
    city: 'Toronto',
  },
  {
    id: 9,
    title: 'Yoga and Wellness Workshop',
    description: 'Explore yoga practices for physical and mental wellness',
    date: new Date(2023, 8, 12, 15, 0, 0, 0),
    availableSeats: 25,
    status: 'Active',
    level: 'All Levels',
    attendies: ['Lily', 'Jack', 'Lucas'],
    city: 'Singapore',
  },
  {
    id: 10,
    title: 'Toastmasters Open Mic Night',
    description:
      'Share your thoughts and experiences in a supportive environment',
    date: new Date(2023, 9, 21, 20, 0, 0, 0),
    availableSeats: 15,
    status: 'Active',
    level: 'All Levels',
    attendies: ['Sophie', 'Ethan', 'Mia'],
    city: 'London',
  },
  {
    id: 11,
    title: 'Mental Health Awareness Seminar',
    description: 'Learn about mental health and coping strategies',
    date: new Date(2023, 10, 7, 14, 30, 0, 0),
    availableSeats: 30,
    status: 'Active',
    level: 'All Levels',
    attendies: ['Logan', 'Chloe', 'Jackson'],
    city: 'New York',
  },
  {
    id: 12,
    title: 'Confidence Building Workshop',
    description: 'Boost your self-confidence through interactive activities',
    date: new Date(2023, 11, 18, 16, 0, 0, 0),
    availableSeats: 20,
    status: 'Active',
    level: 'Beginner',
    attendies: ['Harper', 'Carter', 'Zoe'],
    city: 'Melbourne',
  },
  {
    id: 13,
    title: 'Holistic Health Webinar',
    description: 'Explore holistic approaches to health and wellness',
    date: new Date(2023, 11, 28, 19, 30, 0, 0),
    availableSeats: 25,
    status: 'Active',
    level: 'Intermediate',
    attendies: ['Abigail', 'Elijah', 'Natalie'],
    city: 'San Francisco',
  },
  {
    id: 14,
    title: 'Storytelling Circle',
    description: 'Share and listen to captivating stories in a friendly circle',
    date: new Date(2024, 0, 8, 18, 0, 0, 0),
    availableSeats: 15,
    status: 'Active',
    level: 'All Levels',
    attendies: ['Isaac', 'Aria', 'Gabriel'],
    city: 'Tokyo',
  },
  {
    id: 15,
    title: 'Guided Stress Relief Session',
    description: 'Relax and relieve stress with guided exercises',
    date: new Date(2024, 1, 5, 20, 0, 0, 0),
    availableSeats: 20,
    status: 'Active',
    level: 'All Levels',
    attendies: ['Amelia', 'Ezra', 'Ava'],
    city: 'Berlin',
  },
];

const initializeDatabase = async (db: Datastore<Meeting>): Promise<void> => {
  await db.insert(initialMeetings);
};

export { initializeDatabase };
