GET http://localhost:3001/meetings

GET http://localhost:3001/meetings/8

GET http://localhost:3001/users

POST http://localhost:3001/users/byId HTTP/1.1
content-type: application/json

{
  "ids": ["u1", "u2"]
}

GET http://localhost:3001/comments/12

POST http://localhost:3001/comments HTTP/1.1
content-type: application/json

{
  "meetingId": 12,
  "text": "test api comment",
  "authorId": "u3",
  "createdDate": "2024-02-18T08:00:00.000Z"
}
