GET http://localhost:3001/meetings

POST http://localhost:3001/meetings HTTP/1.1
content-type: application/json

{
  "id": 1,
  "title": "test",
  "description": "test",
  "date": "10.01.2022",
  "availableSeats": 100,
  "status": "Live",
  "level": "Beginner"
}

GET http://localhost:3001/meetings/1

PUT http://localhost:3001/meetings/1 HTTP/1.1
content-type: application/json

{
  "id": 1,
  "title": "test updated",
  "description": "test",
  "date": "10.01.2022",
  "availableSeats": 101,
  "status": "Live",
  "level": "Beginner"
}

DELETE http://localhost:3001/meetings/1
